### ISSUE TITLE
Sample code?

### ISSUE THREAD

**Issue by ignatandrei** [usausa/common-code-generator#1]
I maintain a list of Roslyn Code Generators at https://ignatandrei.github.io/RSCG_Examples/v2/docs/rscg-examples 

I see yours- but I need some examples in the readme to understand if your code is usable.

Could you provide ?
Thanks
Andrei

**Comment by usausa** [comment]
@ignatandrei 
README.md updated.

**Comment by ignatandrei** [comment]
Thanks!

**Comment by ignatandrei** [comment]
https://ignatandrei.github.io/RSCG_Examples/v2/docs/CommonCodeGenerator
